# Project Euler problem 29
# How many distinct terms are in the sequence generated by 
# a^b for 2<=a<=100 and 2<=b<=100?

def solve():
    dict = {}
    for i in range(2, 101):
        for j in range(2, 101):
            dict[i**j]=1
    print len(dict.keys())
    
if __name__=="__main__":
    solve()